CREATE USER Gregorio WITH PASSWORD '1234';
CREATE USER Estudiante WITH PASSWORD '4321';

GRANT USAGE ON SCHEMA public TO usuario_impactofs;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO usuario_impactofs;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO usuario_impactofs;