-- =====================================================
-- CONSULTAS Y SENTENCIAS SQL - sporty
-- =====================================================

-- 01. Mostrar Bases de Datos.
-- =====================================================

SHOW DATABASES;

-- 02. Usar Base de Datos.
-- =====================================================

USE Sportys;

-- 03. Eliminar Base de Datos.
-- =====================================================
-- SE DEJA COMENTADO PARA EVITAR BORRAR LA BASE DE DATOS

-- DROP DATABASE sporty

-- 04. Mostrar Tablas.
-- =====================================================

SHOW TABLES;

-- 05. Mostrar Columnas de las Tablas.
-- =====================================================

-- ROL
SHOW COLUMNS FROM ROL;
DESCRIBE ROL;

-- USUARIO
SHOW COLUMNS FROM USUARIO;
DESCRIBE USUARIO;

-- USUARIO_ROL
SHOW COLUMNS FROM USUARIO_ROL;
DESCRIBE USUARIO_ROL;

-- ESCUELA
SHOW COLUMNS FROM ESCUELA;
DESCRIBE ESCUELA;

-- EQUIPO
SHOW COLUMNS FROM EQUIPO;
DESCRIBE EQUIPO;

-- CATEGORIA
SHOW COLUMNS FROM CATEGORIA;
DESCRIBE CATEGORIA;

-- ENTRENADOR
SHOW COLUMNS FROM ENTRENADOR;
DESCRIBE ENTRENADOR;

-- ESTUDIANTE
SHOW COLUMNS FROM ESTUDIANTE;
DESCRIBE ESTUDIANTE;

-- EQUIPO_ESTUDIANTE
SHOW COLUMNS FROM EQUIPO_ESTUDIANTE;
DESCRIBE EQUIPO_ESTUDIANTE;

-- TORNEO
SHOW COLUMNS FROM TORNEO;
DESCRIBE TORNEO;

-- TORNEO_EQUIPO
SHOW COLUMNS FROM TORNEO_EQUIPO;
DESCRIBE TORNEO_EQUIPO;

-- HORARIO
SHOW COLUMNS FROM HORARIO;
DESCRIBE HORARIO;

-- NOTIFICACION
SHOW COLUMNS FROM NOTIFICACION;
DESCRIBE NOTIFICACION;

-- CATALOGO
SHOW COLUMNS FROM CATALOGO;
DESCRIBE CATALOGO;

-- CATEGORIA_PRODUCTO
SHOW COLUMNS FROM CATEGORIA_PRODUCTO;
DESCRIBE CATEGORIA_PRODUCTO;

-- 06. Agregar Columnas.
-- =====================================================

ALTER TABLE ROL
ADD DESCRIPCION VARCHAR(300) NOT NULL;

ALTER TABLE USUARIO
ADD DIRECCION VARCHAR(100);

ALTER TABLE EQUIPO
ADD FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP;

-- 07. Renombrar Columnas.
-- =====================================================

ALTER TABLE ROL
CHANGE DESCRIPCION DESC_ROL VARCHAR(300) NOT NULL;

ALTER TABLE USUARIO
CHANGE DIRECCION DIRECCION_USUARIO VARCHAR(100);

-- 08. Eliminar Columnas.
-- =====================================================

ALTER TABLE ROL
DROP COLUMN DESC_ROL;

ALTER TABLE USUARIO
DROP COLUMN DIRECCION_USUARIO;

-- 09. Agregar Valores por Defecto.
-- =====================================================

ALTER TABLE USUARIO
ALTER APELLIDO SET DEFAULT 'Sin apellido';

ALTER TABLE EQUIPO
ALTER LOGO SET DEFAULT 'default.png';

-- 10. Eliminar Valores por Defecto.
-- =====================================================

ALTER TABLE USUARIO
ALTER APELLIDO DROP DEFAULT;

ALTER TABLE EQUIPO
ALTER LOGO DROP DEFAULT;

-- 11. Mostrar Creación de Tablas.
-- =====================================================

SHOW CREATE TABLE ROL;
SHOW CREATE TABLE USUARIO;
SHOW CREATE TABLE USUARIO_ROL;
SHOW CREATE TABLE ESCUELA;
SHOW CREATE TABLE EQUIPO;
SHOW CREATE TABLE CATEGORIA;
SHOW CREATE TABLE ENTRENADOR;
SHOW CREATE TABLE ESTUDIANTE;
SHOW CREATE TABLE EQUIPO_ESTUDIANTE;
SHOW CREATE TABLE TORNEO;
SHOW CREATE TABLE TORNEO_EQUIPO;
SHOW CREATE TABLE HORARIO;
SHOW CREATE TABLE NOTIFICACION;
SHOW CREATE TABLE CATALOGO;
SHOW CREATE TABLE CATEGORIA_PRODUCTO;

-- 12. Eliminar Restricciones.
-- =====================================================

ALTER TABLE USUARIO_ROL
DROP CONSTRAINT fk_usuarioRol_usuario;

ALTER TABLE USUARIO_ROL
DROP CONSTRAINT fk_usuarioRol_rol;

ALTER TABLE ESCUELA
DROP CONSTRAINT fk_escuela_usuario;

ALTER TABLE EQUIPO
DROP CONSTRAINT fk_equipo_escuela;

ALTER TABLE ENTRENADOR
DROP CONSTRAINT fk_entrenador_usuario;

ALTER TABLE ENTRENADOR
DROP CONSTRAINT fk_entrenador_equipo;

ALTER TABLE ESTUDIANTE
DROP CONSTRAINT fk_estudiante_usuario;

ALTER TABLE EQUIPO_ESTUDIANTE
DROP CONSTRAINT fk_equipoEstudiante_equipo;

ALTER TABLE EQUIPO_ESTUDIANTE
DROP CONSTRAINT fk_equipoEstudiante_estudiante;

ALTER TABLE TORNEO_EQUIPO
DROP CONSTRAINT fk_torneoEquipo_torneo;

ALTER TABLE TORNEO_EQUIPO
DROP CONSTRAINT fk_torneoEquipo_equipo;

ALTER TABLE HORARIO
DROP CONSTRAINT fk_horario_equipo;

ALTER TABLE NOTIFICACION
DROP CONSTRAINT fk_notificacion_torneo;

ALTER TABLE CATALOGO
DROP CONSTRAINT fk_catalogo_estudiante;

ALTER TABLE CATEGORIA_PRODUCTO
DROP CONSTRAINT fk_categoriaProducto_catalogo;

-- 13. Eliminar Índices.
-- =====================================================

ALTER TABLE USUARIO
DROP INDEX CORREO;

-- 14. Eliminar Llaves Primarias.
-- =====================================================

ALTER TABLE USUARIO_ROL DROP PRIMARY KEY;
ALTER TABLE ESCUELA DROP PRIMARY KEY;
ALTER TABLE EQUIPO DROP PRIMARY KEY;
ALTER TABLE CATEGORIA DROP PRIMARY KEY;
ALTER TABLE ENTRENADOR DROP PRIMARY KEY;
ALTER TABLE ESTUDIANTE DROP PRIMARY KEY;
ALTER TABLE EQUIPO_ESTUDIANTE DROP PRIMARY KEY;
ALTER TABLE TORNEO DROP PRIMARY KEY;
ALTER TABLE TORNEO_EQUIPO DROP PRIMARY KEY;
ALTER TABLE HORARIO DROP PRIMARY KEY;
ALTER TABLE NOTIFICACION DROP PRIMARY KEY;
ALTER TABLE CATALOGO DROP PRIMARY KEY;
ALTER TABLE CATEGORIA_PRODUCTO DROP PRIMARY KEY;

-- 15. Limpiar Registros.
-- =====================================================

TRUNCATE TABLE USUARIO_ROL;
TRUNCATE TABLE ESCUELA;
TRUNCATE TABLE EQUIPO;
TRUNCATE TABLE CATEGORIA;
TRUNCATE TABLE ENTRENADOR;
TRUNCATE TABLE ESTUDIANTE;
TRUNCATE TABLE EQUIPO_ESTUDIANTE;
TRUNCATE TABLE TORNEO;
TRUNCATE TABLE TORNEO_EQUIPO;
TRUNCATE TABLE HORARIO;
TRUNCATE TABLE NOTIFICACION;
TRUNCATE TABLE CATALOGO;
TRUNCATE TABLE CATEGORIA_PRODUCTO;

-- 16. Eliminar Tablas.
-- =====================================================

DROP TABLE USUARIO_ROL;
DROP TABLE ESCUELA;
DROP TABLE EQUIPO;
DROP TABLE CATEGORIA;
DROP TABLE ENTRENADOR;
DROP TABLE ESTUDIANTE;
DROP TABLE EQUIPO_ESTUDIANTE;
DROP TABLE TORNEO;
DROP TABLE TORNEO_EQUIPO;
DROP TABLE HORARIO;
DROP TABLE NOTIFICACION;
DROP TABLE CATALOGO;
DROP TABLE CATEGORIA_PRODUCTO;

-- 17. Crear Nueva Tabla.
-- =====================================================

CREATE TABLE IF NOT EXISTS PARTIDO (
    idPARTIDO INT NOT NULL AUTO_INCREMENT,
    FECHA_PARTIDO DATE NOT NULL,
    HORA_PARTIDO TIME NOT NULL,
    LUGAR VARCHAR(100) NOT NULL,
    MARCADOR_LOCAL INT DEFAULT 0,
    MARCADOR_VISITA INT DEFAULT 0,

    idTORNEO INT NOT NULL,

    PRIMARY KEY (idPARTIDO),

    CONSTRAINT fk_partido_torneo
        FOREIGN KEY (idTORNEO)
        REFERENCES TORNEO(idTORNEO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE = InnoDB;

-- 18. Renombrar Tabla.
-- =====================================================

RENAME TABLE CATALOGO TO PRODUCTOS;